version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_laliga
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liga_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  golang:
    build: .
    container_name: backend_laliga
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: